# Stress tensor rotation

This notebook computes the stress tensor after one/several rotations around the axes of the coordinate system

**How to use:**
1. Run the cell below to define the function.
2. Modify `sigma` and `Rx(10.0) @ Rz(30.0) @ Ry(45.0)` as needed and run the execution cells to see the results.


In [2]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [11]:
# --- Initial stress tensor in principal coordinates (MPa) ---
sigma = np.diag([500.0, 0.0, 0.0])

print("User-defined stress tensor (MPa):\n", sigma)

User-defined stress tensor (MPa):
 [[500.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]]


In [12]:
# Rotation matrixes (definitions)

def Rx(deg):
    a = np.deg2rad(deg)
    return np.array([
        [1.0,       0.0,        0.0],
        [0.0,  np.cos(a),  np.sin(a)],
        [0.0, -np.sin(a),  np.cos(a)]
    ])

def Ry(deg):
    a = np.deg2rad(deg)
    return np.array([
        [ np.cos(a), 0.0, -np.sin(a)],
        [ 0.0,       1.0,  0.0      ],
        [ np.sin(a), 0.0,  np.cos(a)]
    ])

def Rz(deg):
    a = np.deg2rad(deg)
    return np.array([
        [ np.cos(a),  np.sin(a), 0.0],
        [-np.sin(a),  np.cos(a), 0.0],
        [ 0.0,        0.0,       1.0]
    ])

In [19]:
# --- Combined rotation of coordinate system ---
# Order: rotate around y by 45°, then z by 30°, then x by 10°
Q = Rx(10.0) @ Rz(30.0) @ Ry(45.0) # multiplication of rotation matrixes in inverse order

print("Global rotation matrix Q:\n", Q)

Global rotation matrix Q:
 [[ 0.612  0.5   -0.612]
 [-0.225  0.853  0.471]
 [ 0.758 -0.15   0.635]]


In [20]:
# --- Transform stress tensor to new coordinate system ---
sigma_new = Q @ sigma @ Q.T

print("\nTransformed stress tensor σ' (MPa):\n", sigma_new)


Transformed stress tensor σ' (MPa):
 [[187.5   -69.013 232.015]
 [-69.013  25.401 -85.397]
 [232.015 -85.397 287.099]]
